{{- $MAIN_OBJECT_BLOCK := "configValues" -}}
{{- $COMPONENT_NAME := "backend" -}}
{{- $DATA := include "tsServerBoilerplaiteData" . -}}

{{- define "tsServerBoilerplaiteData" -}}
{{- $CONFIG_MANAGER_OBJECT := include "common.tplvalues.getGlobalObject" (dict "objName" "configManagment" "context" .) | fromYaml }}
{{- if not $CONFIG_MANAGER_OBJECT.enabled -}}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
{{- end }}
{{- $secrets := (include "common.tplvalues.getGlobalObject" (dict "objName" "secrets" "context" .)) | fromYamlArray -}}
{{- range $secrets }}
  {{- if eq .name "root-ca" }}
NODE_EXTRA_CA_CERTS: {{ printf "%s/%s" .path (first .data).key | quote }}
  {{- end }}
{{- end }}
  npm_config_cache: /tmp/
{{- end -}}

{{ include "mc-chart.configmap" (dict "MAIN_OBJECT_BLOCK" $MAIN_OBJECT_BLOCK "COMPONENT_NAME" $COMPONENT_NAME "DATA" $DATA "WITH_TELEMETRY_TRACING" true "WITH_TELEMETRY_METRICS" true "context" .)}}
