name: "Match chert version"

on:
  push:
    tags:
      - "v*"

env:
  HELM_EXPERIMENTAL_OCI: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  user-input:
    runs-on: ubuntu-latest
    steps:
      - name: Prompt User for Input
        id: input
        run: |
          read -p "Enter a value (press Enter to skip): " userInput
          echo "::set-output name=userInput::$userInput"