name: pull_request

on: pull_request

permissions:
  contents: read
  pull-requests: read

jobs:
  eslint:
    name: Run TS Project eslint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [22.x, 24.x]

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v5

      - name: Init Nodejs
        uses: MapColonies/shared-workflows/actions/init-npm@remove-unnecessary-actions
        with:
          node-version: ${{ matrix.node }}

      - name: Run TS Project linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          eslint_extensions: ts
          tsc: true

  openapi-lint:
    name: Run OpenAPI lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v5

      - name: Init Nodejs
        uses: MapColonies/shared-workflows/actions/init-npm@remove-unnecessary-actions

      - name: OpenAPI Lint Checks
        run: npx @redocly/cli lint --format=github-actions openapi3.yaml

  helm-lint:
    name: Run Helm lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Helm Lint Checks
        uses: MapColonies/shared-workflows/actions/helm-lint@remove-unnecessary-actions

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [22.x, 24.x]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Init Nodejs
        uses: MapColonies/shared-workflows/actions/init-npm@remove-unnecessary-actions
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests
        run: npm run test

      - uses: actions/upload-artifact@v4
        with:
          name: Test Reporters Node-${{ matrix.node }}
          path: reports/**

  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
